### ISSUE TITLE
wrong boost url

### ISSUE THREAD

**Issue by mrphrazer** [fabsx00/bjoern#4]
Hi!

The url of boost is wrong. It should be 

http://www.boost.org/users/history/version_1_53_0.html

**Comment by fabsx00** [comment]
Thanks, fixed.

**Comment by mrphrazer** [comment]
I don't want to create a new issue for that:

Debian jessie does also requiere ghostscript.  Apart from that, the instructions are fine. Thanks for the documentation!

**Comment by fabsx00** [comment]
Fixed. Thanks.
